### ISSUE TITLE
Trouver une base de données qui fournit les accès via API

### ISSUE THREAD

**Issue by Marimout** [Marimout/chasse-aux-bugs#2]
... ou coder les APIs s'il n'y a pas une telle base

**Comment by Hatscat** [comment]
en fait je pense qu'on devrait utiliser une solution de base de donnée client side, comme WebSQL DB ou IndexedDB, ça serait bien plus simple et c'est suffisant pour le jeu. quelques ressources à ce sujet:
* http://html5doctor.com/introducing-web-sql-databases/
* https://www.html5rocks.com/en/tutorials/webdatabase/websql-indexeddb/ 
* https://developer.mozilla.org/fr/docs/Web/API/API_IndexedDB

**Comment by Hatscat** [comment]
cette lib m'a l'air bien: https://github.com/agershun/alasql
reste a trouvé une lib qui fait office de client à cette db

**Comment by Hatscat** [comment]
-> no lib, à la main :)
